# -*- coding: utf-8 -*-
"""
Created on Fri Sep 17 09:04:59 2021

@author: HOME
"""

import turtle
bob=turtle.Turtle()
bob.speed(2)
bob.getscreen().bgcolor("light green")

bob.penup()
bob.left(90)
bob.forward(200)
bob.right(90)
bob.pendown()

#tika1
bob.color("light green","white")
bob.begin_fill()
bob.left(90)
bob.forward(25)
bob.right(90)
bob.forward(25)
bob.right(90)
bob.forward(25)
bob.right(90)
bob.forward(25)
bob.end_fill()

#tika2
bob.color("black")
bob.begin_fill()
bob.penup()
bob.left(90)
bob.forward(10)
bob.forward(10)
bob.pendown()
bob.left(90)
bob.forward(125)
bob.left(90)
bob.forward(10)
bob.left(90)
bob.forward(125)
bob.left(90)
bob.forward(10)
bob.end_fill()

#tika3
bob.begin_fill()
bob.penup()
bob.forward(20)
bob.pendown()
bob.left(90)
bob.forward(125)
bob.left(90)
bob.forward(10)
bob.left(90)
bob.forward(125)
bob.left(90)
bob.forward(10)
bob.end_fill()

#tika4
bob.begin_fill()
bob.penup()
bob.forward(20)
bob.pendown()
bob.left(90)
bob.forward(125)
bob.left(90)
bob.forward(10)
bob.left(90)
bob.forward(125)
bob.left(90)
bob.forward(10)
bob.end_fill()

#face+trunk+eye+ear+plate1&2+laddu
bob.begin_fill()
bob.penup()
bob.forward(20)
bob.pendown()
bob.left(90)
bob.forward(150)
bob.right(90)
bob.forward(150)
bob.right(90)
bob.forward(75)
bob.left(90)

#trunk
for i in range(90):
	bob.left(.5)
	bob.forward(2.5)
bob.right(90)
bob.forward(75)
bob.right(90)
for i in range(90):
	bob.right(.5)
	bob.forward(3.2)
bob.forward(145)
bob.end_fill()
bob.penup()
bob.back(50)
bob.right(90)
bob.forward(15)


#eye
bob.color("black","white")
bob.begin_fill()
bob.pendown()
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.end_fill()

#ear
bob.color("black")
bob.penup()
bob.forward(160)
bob.left(90)
bob.forward(50)
bob.pendown()
bob.begin_fill()
bob.right(90)
bob.forward(35)
bob.right(45)
bob.forward(35)
bob.right(45)
bob.forward(60)
bob.left(45)
bob.forward(15)
bob.left(45.2)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.right(90)
bob.forward(20)
bob.left(45)
bob.forward(15)
bob.left(45.1)
bob.forward(60)
bob.right(45)
bob.forward(35)
bob.right(45)
bob.forward(35)
bob.right(90)
bob.forward(15)
bob.right(90)
bob.forward(30)
bob.left(45.5)
bob.forward(25)
bob.left(45.5)
bob.forward(60)
bob.right(45)
bob.forward(20)
bob.left(90)
bob.forward(20)
bob.right(45.5)
bob.forward(60)
bob.left(45)
bob.forward(25)
bob.left(45)
bob.forward(28)
bob.right(90)
bob.forward(13)
bob.end_fill()

bob.penup()
bob.back(180)
bob.back(185)
bob.pendown()

#plate1
bob.begin_fill()
bob.right(45)
bob.forward(15)
bob.right(90)
bob.forward(55)
bob.left(90)
bob.forward(55)
bob.right(90)
bob.forward(15)
bob.right(90)
bob.forward(70)
bob.right(90)
bob.forward(70)
bob.end_fill()

#laddu
bob.color("light green","white")
bob.penup()
bob.forward(20)
bob.right(137)
bob.forward(93)
bob.left(45)
bob.pendown()
bob.begin_fill()
bob.circle(40)
bob.end_fill()

#plate2
bob.color("black")
bob.begin_fill()
bob.penup()
bob.left(135)
bob.forward(230)
bob.pendown()
bob.right(45)
bob.forward(70)
bob.left(90)
bob.forward(70)
bob.left(90)
bob.forward(15)
bob.left(90)
bob.forward(55)
bob.right(90)
bob.forward(55)
bob.left(90)
bob.forward(15)
bob.end_fill()

bob.penup()
bob.goto(-300,-200)
bob.write("Created by - Dilip Prasad")

turtle.done()



